


[functions.payment-gateway]
enabled = true
verify_jwt = true
entrypoint = "./functions/payment-gateway/index.ts"

[functions.send-ticket-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-ticket-email/index.ts"

[functions.send-otp]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-otp/index.ts"


[functions.register-creator]
enabled = true
verify_jwt = false
entrypoint = "./functions/register-creator/index.ts"

[functions.redeem-voucher]
enabled = true
verify_jwt = false
entrypoint = "./functions/redeem-voucher/index.ts"

[functions.create-va]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-va/index.ts"

[functions.inquiry-status]
enabled = true
verify_jwt = false
import_map = "./functions/inquiry-status/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/inquiry-status/index.ts"
[functions.order-fulfillment]
enabled = true
verify_jwt = false
entrypoint = "./functions/order-fulfillment/index.ts"

[functions.transfer-va]
enabled = true
verify_jwt = false
entrypoint = "./functions/transfer-va/index.ts"

[functions.transfer-va-payment]
enabled = true
verify_jwt = false
entrypoint = "./functions/transfer-va-payment/index.ts"

[functions.api]
enabled = true
verify_jwt = false
entrypoint = "./functions/api/index.ts"

[functions.api]
enabled = true
verify_jwt = false
entrypoint = "./functions/api/index.ts"
